name: Static analysis

on: [push, pull_request]

jobs:
  build:
    name: Build PHP
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        php: ['php8.1']
        experimental: [false]
        include:
          - os: 'ubuntu-20.04'
            php: 'php7.4'
            experimental: false
          - os: 'ubuntu-20.04'
            php: 'php8.0'
            experimental: false
          - os: 'ubuntu-20.04'
            php: 'php8.1'
            experimental: false

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/${{ matrix.php }}
          php -v
      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version
      - name: Install
        run: |
          composer install
      - name: PHPStan
        run: |
          php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration phpstan.neon --debug
